# This is a basic workflow to help you get started with Actions

name: CICD-SEC-1 pipeline_external_dependencies (push) (CMD)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push: #branch github.ref
    branches: [ "main" ]
  #pull_request: #branch github.head_ref
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  #GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  XY_USERNAME: ${{ secrets.XY_USERNAME }}
  XY_PASSWORD: ${{ secrets.XY_PASSWORD }}
  #XY_URL: ${{ secrets.XY_URL }}
  XY_URL: 'https://apidev.xygeni.io/deps-doctor-service'
  XY_URL_SCANNER: 'https://get.xygeni.io/latest/scanner/install.sh'
  XY_PRJ_NAME: GH-CICD1-pipeline_external_dependencies-push-${GITHUB_REF##*/}-CMD

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Xy Environment
        run: |
          echo XY_URL_SCANNER [${{ env.XY_URL_SCANNER }}]
          echo XY_PRJ_NAME [${{ env.XY_PRJ_NAME }}]
          

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 #8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '0'