name: Do Xygeni scan

on:
  workflow_call:


jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '10'
      - name: My First Line
        run: echo "Hola from called workflow"
